export const REGISTER_FIELD = [
  {
    type: 'text',
    id: 'name',
    name: 'name',
    label: 'Name *',
    color: 'primary',
    variant: 'outlined',
    margin: 'normal',
    autoComplete: 'Name',
    fullWidth: true,
  },
  {
    type: 'text',
    id: 'email',
    name: 'email',
    label: 'Email *',
    color: 'primary',
    variant: 'outlined',
    margin: 'normal',
    autoComplete: 'Email',
    fullWidth: true,
  },
  {
    type: 'password',
    id: 'password',
    name: 'password',
    label: 'Password *',
    color: 'primary',
    variant: 'outlined',
    margin: 'normal',
    autoComplete: 'Password',
    fullWidth: true,
  },
  {
    type: 'password',
    id: 'confirmPassword',
    name: 'confirmPassword',
    label: 'Confirm Password *',
    color: 'primary',
    variant: 'outlined',
    margin: 'normal',
    autoComplete: 'Confirm Password',
    fullWidth: true,
  },
];

export const LOGIN_FIELD = [
  {
    type: 'text',
    id: 'email',
    name: 'email',
    label: 'Email *',
    color: 'primary',
    variant: 'outlined',
    margin: 'normal',
    autoComplete: 'Email',
    fullWidth: true,
  },
  {
    type: 'password',
    id: 'password',
    name: 'password',
    label: 'Password *',
    color: 'primary',
    variant: 'outlined',
    margin: 'normal',
    autoComplete: 'Password',
    fullWidth: true,
  },
];
